services:
  mysql:
    image: mysql:latest
    ports:
      - 33306:3306
    environment:
      - MYSQL_DATABASE=douyin
      - MYSQL_USER=hairline
      - MYSQL_PASSWORD=hairline
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    volumes:
      - dy-mysql:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - 36379:6379
    command: redis-server --requirepass hairline
    
volumes:
  dy-mysql:
