// Code generated by hertz generator.

package main

import (
	"douyin_backend/biz/config"
	"douyin_backend/biz/dal"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {
	err := config.InitConfig("config.yml")
	if err != nil {
		fmt.Println(err)
		return
	}
	hlog.SetLevel(hlog.LevelTrace)
	dal.Init()
	h := server.Default(server.WithHostPorts(config.Cfg.Hertz.HostPort), server.WithMaxRequestBodySize(128*1024*1024))
	register(h)
	h.Spin()
}
