// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	core "douyin_backend/biz/router/core"
	interact "douyin_backend/biz/router/interact"
	socialize "douyin_backend/biz/router/socialize"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	socialize.Register(r)

	interact.Register(r)

	core.Register(r)
}
